name: Update UniStore and pages

on:
  push:
    branches: [ main ]
    paths: [ generate.py, requirements.txt, "sets/**", .github/workflows/update.yml ]

jobs:
  run:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm

    steps:
    - uses: actions/checkout@v1
    
    - name: Install packages
      run: |
        echo deb http://deb.debian.org/debian stable main contrib non-free >> /etc/apt/sources.list
        sudo apt-get update
        sudo apt-get install python3-pip -y
        pip3 install -r requirements.txt

    - name: Delete old pages
      run: rm -rf docs/_*/*.md

    - name: Run generate.py
      run: |
        export PATH=$PATH:/opt/devkitpro/tools/bin
        python3 generate.py ${{ secrets.GITHUB_TOKEN }}

    - name: Push changes
      uses: github-actions-x/commit@v2.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: main
        commit-message: Update UniStore and pages
        force-add: false
        files: "*"
        name: TWLBot
        email: flamekat54@aol.com 
